version: '3.8'

# Build configuration
x-build: &build-config
  build:
    context: .
    dockerfile: Dockerfile
    platforms:
      - linux/arm64

services:
  preparer:
      platform: linux/arm64
      restart: no
      image: watcher:latest
      <<: *build-config
      volumes:
        - .:/app
        - ./.env.development:/app/.env.development:ro
      networks:
        - watcher-network
      environment:
        - RUN_AS=PREPARER

  testserver:
    platform: linux/arm64
    restart: always
    image: watcher:latest
    <<: *build-config
    volumes:
      - .:/app
      - ./.env.development:/app/.env.development:ro
    ports:
      - 8000:8000
      - 8080:8080
    networks:
      - watcher-network
    environment:
      - RUN_AS=TEST_SERVER

  watcher:
    platform: linux/arm64
    restart: no
    image: watcher:latest
    <<: *build-config
    privileged: true
    volumes:
      - .:/app
      - ./.env.development:/app/.env.development:ro
    networks:
      - watcher-network
    ports:
      - 8080:8080
    depends_on:
      preparer:
        condition: service_completed_successfully

networks:
  watcher-network:
    driver: bridge