global:
  dataway:
    # Token will be provided via ArgoCD parameters
    token: ""
  tags:
    project: "site-uptime-watcher"
    env: "prod"

daemonset:
  enabled: true
  # Use the official Datakit image
  image:
    repository: guance/datakit
    tag: latest
    pullPolicy: IfNotPresent
  # Configure resources
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  # Configure volumes
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
    - name: kubernetes-socket
      hostPath:
        path: /var/run/kubernetes

  # Configure volume mounts
  volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
    - name: kubernetes-socket
      mountPath: /var/run/kubernetes

# Configure inputs
inputs:
  # Enable Prometheus input
  prom:
    enabled: true
    urls:
      - http://localhost:9529/metrics
    interval: 10s
  
  # Enable Docker input
  docker:
    enabled: true
    endpoint: unix:///var/run/docker.sock
    interval: 10s
  
  # Enable Kubernetes input
  kubernetes:
    enabled: true
    url: https://kubernetes.default
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    ssl_ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    interval: 10s

# Configure service account
serviceAccount:
  create: true
  name: datakit-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::954976318202:role/datakit-role 