apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datakit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/lipingtababa/SiteUptimeWatcher.git
    targetRevision: HEAD
    path: infra/application/datakit
  destination:
    server: https://kubernetes.default.svc
    namespace: watcher
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 