apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lipingtababa/SiteUptimeWatcher.git
    targetRevision: HEAD
    path: infra/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: watcher
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
