apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: watcher
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lipingtababa/SiteUptimeWatcher.git
    targetRevision: HEAD
    path: infra/application
    kustomize:
      images:
      - 954976318202.dkr.ecr.us-east-1.amazonaws.com/watcher:latest
  destination:
    server: https://kubernetes.default.svc
    namespace: watcher
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
