apiVersion: v1
kind: ConfigMap
metadata:
  name: datakit-config
  namespace: watcher
data:
  datakit.conf: |
    [global_tags]
      project = "site-uptime-watcher"
      env = "prod"
    
    [dataway]
      urls = ["https://openway.guance.com?token=${DATAKIT_TOKEN}"]
    
    [logging]
      level = "info"
      log = "/var/log/datakit/log"
    
    [http_api]
      listen = "0.0.0.0:9529"
    
    [inputs]
      [[inputs.prom]]
        urls = ["http://localhost:9529/metrics"]
        interval = "10s"
    
    [[inputs.docker]]
      endpoint = "unix:///var/run/docker.sock"
      interval = "10s"
    
    [[inputs.kubernetes]]
      url = "https://kubernetes.default"
      bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
      ssl_ca_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
      interval = "10s"
---
apiVersion: v1
kind: Secret
metadata:
  name: datakit-secret
  namespace: watcher
type: Opaque
stringData:
  token: "YOUR_DATAKIT_TOKEN_HERE" 