apiVersion: v1
kind: ConfigMap
metadata:
  name: datakit-config
  namespace: watcher
data:
  datakit.yaml: |
    # DataKit configuration
    dataway:
      urls: ["https://eu1-openway.truewatch.com?token=${DATAKIT_TOKEN}"]
    
    # Enable default collectors
    default_enabled_inputs: ["cpu", "disk", "diskio", "mem", "swap", "system", "hostobject", "net", "host_processes", "container"]
    
    # Global tags
    global_tags:
      project: "site-uptime-watcher"
      env: "prod"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datakit
  namespace: watcher
  labels:
    app: datakit
    app.kubernetes.io/part-of: site-uptime-watcher
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    matchLabels:
      app: datakit
  template:
    metadata:
      labels:
        app: datakit
    spec:
      containers:
      - name: datakit
        image: guance/datakit:latest
        imagePullPolicy: Always
        env:
        - name: DATAKIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: datakit-token
              key: token
        - name: ENV_DATAWAY
          value: "https://eu1-openway.truewatch.com?token=$(DATAKIT_TOKEN)"
        - name: ENV_DEFAULT_ENABLED_INPUTS
          value: "cpu,disk,diskio,mem,swap,system,hostobject,net,host_processes,container"
        - name: ENV_GLOBAL_TAGS
          value: "project=site-uptime-watcher,env=prod"
        volumeMounts:
        - name: datakit-config
          mountPath: /usr/local/datakit/conf.d
        - name: datakit-data
          mountPath: /usr/local/datakit/data
        - name: proc
          mountPath: /proc
          readOnly: true
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: docker-sock
          mountPath: /var/run/docker.sock
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: datakit-config
        configMap:
          name: datakit-config
      - name: datakit-data
        emptyDir: {}
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock 