apiVersion: v1
kind: ConfigMap
metadata:
  name: datakit-config
  namespace: watcher
data:
  datakit.conf: |
    [global_tags]
      project = "site-uptime-watcher"
      env = "prod"
    
    [dataway]
      urls = ["https://openway.guance.com?token=${DATAKIT_TOKEN}"]
    
    [logging]
      level = "info"
      log = "/var/log/datakit/log"
    
    [http_api]
      listen = "0.0.0.0:9529"
    
    [inputs]
      [[inputs.prom]]
        urls = ["http://localhost:9529/metrics"]
        interval = "10s"
    
    [[inputs.docker]]
      endpoint = "unix:///var/run/docker.sock"
      interval = "10s"
    
    [[inputs.kubernetes]]
      url = "https://kubernetes.default"
      bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
      ssl_ca_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
      interval = "10s"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datakit
  namespace: watcher
  labels:
    app: datakit
spec:
  selector:
    matchLabels:
      app: datakit
  template:
    metadata:
      labels:
        app: datakit
    spec:
      serviceAccountName: datakit-sa
      containers:
      - name: datakit
        image: guance/datakit:latest
        ports:
        - containerPort: 9529
        volumeMounts:
        - name: config
          mountPath: /usr/local/datakit/conf.d
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: kubernetes-socket
          mountPath: /var/run/kubernetes
        env:
        - name: DATAKIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: datakit-secret
              key: token
      volumes:
      - name: config
        configMap:
          name: datakit-config
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: kubernetes-socket
        hostPath:
          path: /var/run/kubernetes
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: datakit-sa
  namespace: watcher
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::954976318202:role/datakit-role
---
apiVersion: v1
kind: Secret
metadata:
  name: datakit-secret
  namespace: watcher
type: Opaque
stringData:
  token: "YOUR_DATAKIT_TOKEN_HERE" 