apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
  namespace: watcher
spec:
  template:
    spec:
      serviceAccountName: watcher-sa
      containers:
      - name: db-init
        image: 975688691016.dkr.ecr.us-east-1.amazonaws.com/watcher:latest
        command: ["python3", "-c", "from utils import load_config; from keeper import Keeper; from asyncio import Queue; load_config(); Keeper(Queue()).check_readiness()"]
      restartPolicy: OnFailure
  backoffLimit: 4 