apiVersion: v1
kind: Namespace
metadata:
  name: watcher
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: watcher-service
  namespace: watcher
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::954976318202:role/watcher-pod-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher
  namespace: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      labels:
        app: watcher
    spec:
      serviceAccountName: watcher-service
      containers:
      - name: watcher
        image: 954976318202.dkr.ecr.us-east-1.amazonaws.com/watcher:latest
        ports:
        - containerPort: 8000
        env:
        - name: AWS_REGION
          value: us-east-1
        - name: AWS_ACCOUNT
          value: "954976318202"
        - name: EKS_CLUSTER
          value: idp
        - name: NAMESPACE
          value: watcher
