apiVersion: v1
kind: Namespace
metadata:
  name: watcher
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: watcher-sa
  namespace: watcher
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$(AWS_ACCOUNT_ID):role/watcher-pod-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher
  namespace: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      labels:
        app: watcher
    spec:
      serviceAccountName: watcher-sa
      containers:
      - name: watcher
        image: 975688691016.dkr.ecr.us-east-1.amazonaws.com/watcher:latest
        ports:
        - containerPort: 8000
        env:
        - name: AWS_REGION
          value: us-east-1
        - name: AWS_ACCOUNT
          value: "975688691016"
        - name: EKS_CLUSTER
          value: idp
        - name: NAMESPACE
          value: watcher
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
