name: Deploy to AWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: watcher
  EKS_CLUSTER: idp
  NAMESPACE: watcher
  AWS_ACCOUNT: 954976318202
  ARGOCD_APP_NAME: watcher

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      image_tag: ${{ github.sha }}
    secrets: inherit

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/github-action
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}

      - name: Create namespace if not exists
        run: kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -

      - name: Update deployment
        run: |
          # Check if deployment exists
          if kubectl get deployment watcher -n ${{ env.NAMESPACE }} &> /dev/null; then
            # Update the image in the existing deployment
            kubectl set image deployment/watcher -n ${{ env.NAMESPACE }} watcher=${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          else
            # Apply the deployment if it doesn't exist
            kubectl apply -f infra/application/watcher.deployment.yaml
            # Update the image
            kubectl set image deployment/watcher -n ${{ env.NAMESPACE }} watcher=${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          fi
          
          # Wait for deployment to be ready
          kubectl rollout status deployment/watcher -n ${{ env.NAMESPACE }} --timeout=300s
            
      - name: Notify deployment status
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const status = ${{ job.status }} === 'success' ? '✅' : '❌';
            const message = `Deployment ${status} to AWS\nCommit: ${{ github.sha }}\nRun: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`;
            
            // Only create a comment if this is a PR
            if (context.issue.number) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
            }