name: Build 
run-name: ${{ github.actor }} is building ${{ github.repository }}
permissions:
    id-token: write
    contents: read
env:
    AWS_REGION: us-east-1
    IMAGE_TAG: ${{ github.sha }}
    AWS_ACCOUNT: 954976318202
    EKS_CLUSTER: idp
    NAMESPACE: watcher
    ECR_REPOSITORY: watcher
on: 
  push:
  workflow_call:
    inputs:
      image_tag:
        description: 'The tag to use for the Docker image'
        required: false
        type: string
        default: ${{ github.sha }}
    secrets:
      AWS_REGION:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v4

      - name: Prepare QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build Docker image
        run: |
            docker buildx create --name arm64-builder --use
            docker buildx build --platform linux/arm64 --load -t watcher:${{ inputs.image_tag || env.IMAGE_TAG }} .

      - name: Run pytest
        run: docker run watcher:${{ inputs.image_tag || env.IMAGE_TAG }} pytest ./test -v

      - name: Run pylint
        run: docker run watcher:${{ inputs.image_tag || env.IMAGE_TAG }} pylint ./src

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/github-action
          role-session-name: github
          aws-region: ${{ env.AWS_REGION }}

      - name: Push Docker image
        run: |
            aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
            docker tag watcher:${{ inputs.image_tag || env.IMAGE_TAG }} ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ inputs.image_tag || env.IMAGE_TAG }}
            docker tag watcher:${{ inputs.image_tag || env.IMAGE_TAG }} ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
            docker push ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ inputs.image_tag || env.IMAGE_TAG }}
            docker push ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
