name: Build and Deploy Worker

on:
  push:
    branches: [ main ]
    paths:
      - 'src/worker/**'
      - 'src/utils.py'
      - 'src/keeper.py'
      - 'src/endpoint.py'
      - 'infra/worker/**'
      - 'infra/application/worker.deployment.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/worker/**'
      - 'src/utils.py'
      - 'src/keeper.py'
      - 'src/endpoint.py'
      - 'infra/worker/**'
      - 'infra/application/worker.deployment.yaml'

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT: 975688691016
  ECR_REPOSITORY: watcher
  IMAGE_TAG: ${{ github.sha }}
  EKS_CLUSTER: idp
  NAMESPACE: watcher

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Run worker tests
      run: |
        pytest src/worker/tests
        pylint src/worker

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/github-action
        role-session-name: github
        aws-region: us-east-1
        audience: sts.amazonaws.com

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Worker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: infra/worker/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Update kube config
      run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}

    - name: Deploy to EKS
      run: |
        kubectl apply -f infra/application/watcher.deployment.yaml
        kubectl -n ${{ env.NAMESPACE }} set image deployment/watcher worker=${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
